apiVersion: v1
kind: ConfigMap
metadata:
  name: oss-device-message-api-health-config
  labels:
    app: device-message-api
    group: api
    ms: {{ .Values.ms | quote }}
data:
  api_readiness.sh: |+
    #!/bin/sh
    wget -O /usr/local/tomcat/metrics-readiness http://localhost:8080/device-message/metrics
    file="/usr/local/tomcat/metrics-readiness"
    if [ -f "$file" ]
    then
      echo "$file found."
      serviceHealth=$(grep SERVICE_HEALTH $file | cut -d' ' -f2)
      if [ "$serviceHealth" == "1.0" ]; then
        echo "Service is unhealthy during readiness check"
        rm "$file"
        exit 1
      else
        echo "Service is healthy during readiness check"
      fi
        rm "$file"
    else
      echo "$file not found."
    fi
  api_liveness.sh: |+
    #!/bin/sh
    wget -O /usr/local/tomcat/metrics-liveness http://localhost:8080/device-message/metrics
    file="/usr/local/tomcat/metrics-liveness"
    if [ -f "$file" ]
    then
      echo "$file found."
      serviceHealth=$(grep SERVICE_HEALTH $file | cut -d' ' -f2)
      if [ "$serviceHealth" == "1.0" ]; then
        echo "Service is unhealthy during liveness check"
        rm "$file"
        exit 1
      else
        echo "Service is healthy during liveness check"
      fi
        rm "$file"
    else
      echo "$file not found."
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oss-device-message-api-config
  labels:
    app: device-message-api
    group: api
    ms: {{ .Values.ms | quote }}
data:
  log-level: "INFO"
  api_registry_enabled: {{ .Values.api_gateway.api_registry_enabled | quote }}
  api_registry_service_name: {{ .Values.api_gateway.api_registry_service_name | quote }}
  api_gateway_service_name: {{ .Values.api_gateway.api_gateway_service_name | quote }}
  api_security_enabled: {{ .Values.api_gateway.api_security_enabled | quote }}
  api_context-path: "/device-message"
  scopes_override_enabled: {{ .Values.api_gateway.scopes_override_enabled | quote }}
  spring_application_version: "1.0"
  spring_application_name: "device-message-api"
  spring_application_servicename: "oss-device-message-api-int-svc"
  openapi_path_include: "/{version}/devices/**"
  mongodb_name: {{ .Values.mongodb.databaseName | quote }}
  mongodb_port: {{ .Values.mongodb.port | quote }}
  mongodb_hosts: {{ .Values.mongodb.host | quote }}
  mongodb_auth_db: "admin"
  mongodb_qr_global_svc: {{ .Values.mongodb.host | quote }}
  mongodb_read_preference: "primaryPreferred"
  mongodb_client_cleanup_interval_ms: "20000"
  service_name: "device-message-api"
  mqtt_broker_url: {{ .Values.mqtt.mqtt_broker_url | quote }}
  mqtt_user_name: "haa_api"
  mqtt_user_password: {{ .Values.mqtt.password | quote }}
  mqtt_persistence_base_dir: "/mqtt"
  mqtt_prefix_enabled: {{ .Values.device_message_api.mqtt_prefix_enabled | quote }}
  mqtt_prefix_topic: {{ .Values.device_message_api.mqtt_prefix_topic | quote }} 
  kafka_ssl_enable: "false"
  kafka_producer_service_enabled: "false"
  metrics_prometheus_enabled: "true"
  redis_address: "TO-BE-UPDATED" #<redis-cluster>:<port>
  redis_sentinels: "TO-BE-UPDATED"
  redis_master_name: "redis-sentinel"

  NEVER_BLOCK_FOR_GRAYLOG: "true"
  LOG_LEVEL: {{ .Values.logging.logLevel | quote }}
  REGISTRY_COMMON_LOG_LEVEL: {{ .Values.logging.registryCommonLogLevel | quote }}
  SVC_LOG_LEVEL: {{ .Values.logging.svcLogLevel | quote }}
  SVC_CONSOLE_LOG_LEVEL: {{ .Values.logging.svcConsoleLogLevel | quote }}
  IGNITE_LOG_LEVEL: {{ .Values.logging.igniteLogLevel | quote }}
  STORAGE_LOG_LEVEL: {{ .Values.logging.storageLogLevel | quote }}
  SPRING_LOG_LEVEL: {{ .Values.logging.springLogLevel | quote }}
  CACHE_LOG_LEVEL: {{ .Values.logging.cacheLogLevel | quote }}
  KAFKA_LOG_LEVEL: {{ .Values.logging.kafkaLogLevel | quote }}
  STREAM_BASE_LOG_LEVEL: {{ .Values.logging.streamBaseLogLevel | quote }}
  JAVA_OPTS: {{ .Values.device_message_api.jvmOpts | quote }}
  LOG_APPENDER: {{ .Values.logging.logAppender | quote }}
  GRAYLOG_HOST: {{ .Values.logging.graylogHost | quote }}
  GRAYLOG_PORT: {{ .Values.logging.graylogPort | quote }}
  health_mqtt_monitor_enabled: {{ .Values.device_message_api.health.healthMqtt | quote }}
  health_mongo_monitor_enabled : {{ .Values.device_message_api.health.healthMongo | quote }}
  health_kafka_consumer_group_monitor_enabled : {{ .Values.device_message_api.health.healthKafkaConsumer | quote }}
  health_device_status_backdoor_monitor_enabled : {{ .Values.device_message_api.health.healthDMA | quote }}
  health_dff_feed_backdoor_monitor_enabled : {{ .Values.device_message_api.health.healthDFF | quote }}
  health_kafka_topics_monitor_enabled : {{ .Values.device_message_api.health.healthKafkaTopics | quote }}
  health_redis_monitor_enabled : {{ .Values.device_message_api.health.healthRedis | quote }}
  health_service_failure_retry_thrshold: "2"
  health_service_failure_retry_interval_millis: "2000"
{{- if .Values.device_message_api.extraParams }}
{{ toYaml .Values.device_message_api.extraParams | indent 2 }}
{{- end }}
---
