apiVersion: v1
kind: Secret
metadata:
  name: device-message-api
data:
  mqtt-password: {{ .Values.mqtt.password | b64enc }}
  mongodb-password: {{ .Values.mongodb.password | b64enc }}
  mongodb-user: {{ .Values.mongodb.user | b64enc }}
