apiVersion: v1
data:
  mongodb-password: {{ .Values.mongodb.password | b64enc }}
  mongodb-user: {{ .Values.mongodb.user | b64enc }}
kind: Secret
metadata:
  name: oss-nc-api-secrets
  labels:
    app: notification-api
    group: streaming
    ms: {{ .Values.ms | quote }}
type: Opaque
