apiVersion: v1
kind: Secret
metadata:
  name: vehicle-profile
data:
  mqtt-password: {{ .Values.mqtt.password | b64enc}}
  mongodb-password: {{ .Values.mongodb.password | b64enc}}
  mongodb-user: {{ .Values.mongodb.user | b64enc }}
  vehicle-specification-client-id: {{ .Values.vehiclespecification.vehicle_specification_client_id | b64enc }}
  vehicle-specification-client-secret: {{ .Values.vehiclespecification.vehicle_specification_client_secret | b64enc }}