apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vehicle-profile-api.fullname" . }}
  labels:
    app: vehicle-profile-api
    group: api
    ms: {{ .Values.ms | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vehicle-profile-sp.fullname" . }}
  labels:
    app: vehicle-profile-sp
    group: api
    ms: {{ .Values.ms | quote }}