apiVersion: v1
appVersion: "1.0.0"
description: HiveMQ helm chart that deploys HiveMQ broker, which accepts connections from clients over MQTT protocol.
name: hivemq-cluster
version: 1.0.0
maintainers:
  - name: Akshay Mathur
    email: akshay.mathur@harman.com
