apiVersion: v1
appVersion: "1.0.0"
description: Vehicle profile helm chart that deploys Vehicle profile api.
name: vehicle-profile
version: 1.0.0
maintainers:
  - name: Akshay Mathur
    email: akshay.mathur@harman.com