apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  labels:
    app: postgresql
    release: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
