apiVersion: v1
kind: Secret
metadata:
  name: oss-hivemq-extension-public-key
  labels:
        {{- include "hivemq.labels.standard" . | nindent 4 }}
data:
    publickey.pem: {{ .Values.global.hivemq.uidam.public_key | b64enc | quote }}
