apiVersion: v1
kind: Secret  
metadata:
  name: oss-hivemq-extension-secret
  labels:
    app: {{ template  "hivemq.name" . }} 
type: Opaque
data:
  secret: {{ .Values.global.hivemq.plugin_base.mqtt_user_password| b64enc }}