apiVersion: v1
kind: Service
metadata:
  name: oss-device-shadow-api-int-svc
  labels:
    app: device-shadow-api
    group: api
    ms: {{ .Values.ms | quote }}
    facing: internal
    impl: native
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: tcp
  type: ClusterIP
  selector:
    app: device-shadow-api
