apiVersion: v1
kind: Service
metadata:
    name: oss-notification-sp-svc
    labels:
        app: notification-sp-svc
        group: streaming
        ms: {{ .Values.ms | quote }}
        facing: internal
spec:
    ports:
        - port: 1883
          name: server
    clusterIP: None
    selector:
        app: notification-sp-svc
